version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkbit-tools
    ports:
      - "17814:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    volumes:
      - ./download:/app/download
    restart: unless-stopped
